- name: Create persistent directory
  become: true
  file:
    path: /opt/reviews/persistent
    state: directory
    mode: '0755'
  
- name: Copy persistent compose
  become: true
  copy:
    src: ../../../compose/persistent/docker-compose.yml
    dest: /opt/reviews/persistent/docker-compose.yml
    mode: "0644"

- name: Copy prometheus config
  become: true
  copy:
    src: ../../../compose/persistent/prometheus.yml
    dest: /opt/reviews/persistent/prometheus.yml
    mode: "0644"

- name: Copy env
  become: true
  copy:
    src: ../../../.env
    dest: /opt/reviews/persistent/.env
    mode: "0600"

- name: Create shared docker network
  become: true
  community.docker.docker_network:
    name: reviews_network

- name: Start persistent services
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/reviews/persistent
    state: present
